<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="$(MSBuildProjectDirectory)\..\version.proj" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Version>$(VersionMajor)</Version>
    <DocumentationFile>bin/doc.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>

</Project>
