name: Build doc with docgen & publish it to git hub pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

jobs:
  build:
    name: doc
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      gs-nuget: https://proget.gehtsoft.com/nuget/public-nuget
      gs_nuget: https://proget.gehtsoft.com/nuget/public-nuget
    steps:
    - name: checkout sources
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 8.0.403

    - name: Build release version
      run: |
        dotnet restore
        dotnet build --configuration $config --no-restore

    - name: Setup envionment for doc
      run: |
        echo "gs-nuget=https://proget.gehtsoft.com/nuget/public-nuget" >> $GITHUB_ENV

    - name: build doc
      run: |
        cd doc
        dotnet restore project.proj
        dotnet build project.proj /t:Scan,Raw --no-restore
        dotnet build project.proj /t:MakeDoc --no-restore

    - name: Deploy to GitHub Pages
      if: success()
      uses: crazy-max/ghaction-github-pages@v2
      with:
        target_branch: gh-pages
        build_dir: doc/dst
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
